# -*- coding: utf-8 -*-
"""Advanced Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JyfbSzu0NQN2_xRfSdgP_awWypy-Hc6l
"""

def calculator():

  num1 = float(input('enter'))
  operator = input('enter operator')
  num2 = float(input('enter'))

  if operator =='+':
    result = num1 + num2
  elif  operator  == '-':
    result = num1 - num2
  elif  operator  == '*':
    result = num1 * num2
  elif operator  == '-':
    result= num1 / num2
  else:
    print('Invalid Operator, Please use +,-,/ , *')
  exit()

  print(f'The result of {num1} {operator} {num2} is {result}')

calculator()

